### ISSUE TITLE
AssertionError: Got inconsistent logprobs length : 23 != 22

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [Jeronymous/whisper-timestamped#12]
`!whisper_timestamped "/content/drive/MyDrive/نشيد الهدى The Right Way لمحمد المقيط Muhammed Al Muqit مع الكلمات والترجمة الإنجليزية في الوصف [zVYaS_qXM3Y].flac" --model large --output_dir "/content/drive/MyDrive" --model_dir "/content/drive/MyDrive/Whisper" --language Arabic --device cuda --threads 2 --verbose True`
> <frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
tcmalloc: large alloc 3087007744 bytes == 0xbade000 @  0x7f5d5e218680 0x7f5d5e239824 0x5f97c1 0x649901 0x5c43c6 0x4f327e 0x64e618 0x505163 0x56bbe1 0x5f5ee6 0x56bab6 0x569d8a 0x5f60c3 0x56cc92 0x5f5ee6 0x56bab6 0x569d8a 0x68e267 0x67d9b1 0x67da2f 0x67dad1 0x67fbf7 0x6b8082 0x6b840d 0x7f5d5e017083 0x5faa2e
[00:00.000 --> 00:07.000]  حبّي أنصار الهدى
[00:07.000 --> 00:15.000]  حبّي ركب الفدا
[00:15.000 --> 00:23.000]  وطلّوا بسأر الشاهد
[00:23.000 --> 00:30.000]  وطلّوا بسأر الشاهد
[00:30.000 --> 00:36.000]  لمتى سنظل ربودا نغرق في النوم ونشخر
[00:36.000 --> 00:41.000]  وعن الآذان نسمّ ونغمّض كي لا نيسر
[00:41.000 --> 00:46.000]  لقت أجراس الخطر والحالة جاءت تهذر
[00:46.000 --> 00:52.000]  لمتى نتقع سقول من يمنع زحف المنكر
[00:52.000 --> 00:57.000]  مات الإحساس فصرنا من غير فؤادي يذكر
[00:57.000 --> 01:02.000]  نبصر إخوانا غرقى فنمر كما لا يبصر
[01:02.000 --> 01:08.000]  فلنأمر بالمعروف والنهى عن فعل الشر
[01:08.000 --> 01:15.000]  ولنتركها عذارا دجلا خلقت كين عذار
[01:15.000 --> 01:20.000]  لا أملك فكرة الكلمات تطلع بالدين مورّر
[01:20.000 --> 01:25.000]  أو شخصية تأثير إمّا عندي فلتتققر
[01:25.000 --> 01:31.000]  ما تذكر ليس بعذر إنّي أكبل في يوم المحشر
[01:31.000 --> 01:42.000]  لما لا تتقف فلما لا تترك ما منه تصغّر
[01:42.000 --> 01:52.000]  بأمطار الهدى عبّي ركب الفدا
[01:52.000 --> 01:57.000]  وطلّوا بثأر الشاهدة
[01:57.000 --> 02:03.000]  فتيات اليوم كفاكي تركضت خلف سرابي
[02:03.000 --> 02:08.000]  عودي نحو الإسلام لا تستمعي لذئابي
[02:08.000 --> 02:13.000]  فالشرق دمار فيه والأرض عدو كتابي
[02:13.000 --> 02:19.000]  همّهمو تمسو الديني وكذا نفضل ترابي
[02:19.000 --> 02:24.000]  قتلوا الإنسانية في أعلاقهم بحرابي
[02:24.000 --> 02:31.000]  هجروا الأخلاق فصاروا حيوانات في غابي
[02:31.000 --> 02:36.000]  حيوانات في غابي يا من تعمل للدنيا
[02:36.000 --> 02:41.000]  ليّنفعك فما تعمل أرضاك غدا تصلاهو
[02:41.000 --> 02:47.000]  نارا فيها تتقلقل تعمر في دار فنائي
[02:47.000 --> 02:52.000]  تهدم دار المستقبل وتضيع العمر الغالي
[02:52.000 --> 02:57.000]  وبك الفترة لن تقتل كم سترائي وترائي
[02:57.000 --> 03:03.000]  وتخادع فلا تخجل إن الله عليم لن
[03:03.000 --> 03:08.000]  تخدعه أو تستوفل فغدا إن لن ترجعان
[03:08.000 --> 03:13.000]  غيّك للرشد وتعقل ستنادى بنداءتين
[03:13.000 --> 03:18.000]  يوم على الله ستقبل يا خائب يا كافر
[03:18.000 --> 03:24.000]  يا خاسر يا فاجر يا علف اذهب ولتطلق أجران
[03:24.000 --> 03:30.000]  ممن كنت له تعمال
[03:30.000 --> 03:36.000]  وتعمل لن تال على المانونا
[03:36.000 --> 03:42.000]  برياء أو أنا
[03:42.000 --> 03:45.000]  فلتاكم صاحي راشيد
[03:45.000 --> 03:50.000]  حبي أنصار الهدى
[03:50.000 --> 03:55.000]  عبيئي ركب الفيدى
[03:55.000 --> 04:05.000]  واطمو بسور الشهيد
Traceback (most recent call last):
  File "/usr/local/bin/whisper_timestamped", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/whisper_timestamped/transcribe.py", line 1025, in cli
    result = transcribe_timestamped(
  File "/usr/local/lib/python3.8/dist-packages/whisper_timestamped/transcribe.py", line 491, in transcribe_timestamped
    assert i_end == len(logprobs), f"Got inconsistent logprobs length : {len(logprobs)} != {i_end}"
AssertionError: Got inconsistent logprobs length : 23 != 22

Then It does not output the files.

**Comment by Jeronymous** [comment]
Can you check with the last version please?

Also can you share the file and tell me the full set of options for me to reproduce?

**Comment by MohammedMehdiTBER** [comment]
Same error, sir
On this video, you can replicate:
https://www.youtube.com/watch?v=zVYaS_qXM3Y
[image: image.png]


*A technical, translator, and moderate Sunni Muslim. The antidote of
hypocrites, disbelievers and grooming perisher.*

**Comment by MohammedMehdiTBER** [comment]
> Can you check with the last version please?
> 
> Also can you share the file and tell me the full set of options for me to reproduce?

Same error, sir
On this video, you can replicate:
https://www.youtube.com/watch?v=zVYaS_qXM3Y
![image](https://user-images.githubusercontent.com/78225592/213538287-306cfe5c-788a-46f6-979d-411328d3cc1e.png)

**Comment by Jeronymous** [comment]
Thanks 👍
But it seems that you're not taking the full video.
Just the first 2 minutes or something like this?

**Comment by MohammedMehdiTBER** [comment]
No I have just given you the first video I had the issue with. Not all
tracks suffer from it for some reason I am not sure, maybe the subtitles
are long or something like that?

**Comment by Jeronymous** [comment]
OK thanks for your help. This should be fixed now

**Comment by MohammedMehdiTBER** [comment]
> OK thanks for your help. This should be fixed now

Affirmative, the alignment is currently operational. My gratitude is extended to you, Sir. However, it has been noted that the sentences within the command line interface outputs are not properly aligned until the output file is opened. It is suggested that this issue be addressed to prevent confusion for users.

**Comment by MohammedMehdiTBER** [comment]
> OK thanks for your help. This should be fixed now

I see that the starting time is good for songs but when longing the voice the subtitle does not keep with until It stops.

**Comment by MohammedMehdiTBER** [comment]
> OK thanks for your help. This should be fixed now

The error re happened when I used a very large audio 33min:
[32:48.000 --> 32:53.000]  في كل منواضع
```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\whisper_timestamped.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\whisper_timestamped\transcribe.py", line 1085, in cli
    result = transcribe_timestamped(
  File "C:\Program Files\Python310\lib\site-packages\whisper_timestamped\transcribe.py", line 524, in transcribe_timestamped
    assert abs(segment["avg_logprob"] - avglogprob) < 1e-2, f"Fatal Error: Got inconsistent logprob for segment {i}: {avglogprob} != {segment['avg_logprob']}"
AssertionError: Fatal Error: Got inconsistent logprob for segment 543: -0.34706705808639526 != -0.2806609970571749
```

**Comment by Jeronymous** [comment]
This is not the same error.
I fixed something related to this yesterday: see issue #19
Do you have a version higher or equal to 1.6.5?

**Comment by MohammedMehdiTBER** [comment]
> This is not the same error. I fixed something related to this yesterday: see issue #19 Do you have a version higher or equal to 1.6.5?

No, I have lower
![image](https://user-images.githubusercontent.com/78225592/214516376-3bab6f78-8e1b-4c15-9aa0-7e8458096fef.png)

**Comment by Jeronymous** [comment]
Then upgrade and it should be fixed

**Comment by MohammedMehdiTBER** [comment]
> This is not the same error. I fixed something related to this yesterday: see issue #19 Do you have a version higher or equal to 1.6.5?

Now It did not produce anything:

```python
PS C:\Users\MohammedMehdiTBER> whisper_timestamped "C:\Users\MohammedMehdiTBER\Downloads\نقد أغنية Begin Again Purity Ring.mp3" --model large-v2 --output_dir "C:\Users\MohammedMehdiTBER\Documents" --language Arabic --device cpu --threads 4 --verbose True
C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python310\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python310\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python310\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
2023-01-25 10:11:42.931828: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-01-25 10:11:42.933690: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\whisper_timestamped.exe\__main__.py", line 7, in <module>
  File "C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python310\site-packages\whisper_timestamped\transcribe.py", line 1368, in cli
    result = transcribe_timestamped(
  File "C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python310\site-packages\whisper_timestamped\transcribe.py", line 210, in transcribe_timestamped
    (transcription, words) = _transcribe_timestamped_efficient(model, audio, **alignment_options, **whisper_options, **other_options)
  File "C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python310\site-packages\whisper_timestamped\transcribe.py", line 618, in _transcribe_timestamped_efficient
    assert abs(segment["avg_logprob"] - avglogprob) < 1e-2, f"Fatal Error: Got inconsistent logprob for segment {i}: {avglogprob} != {segment['avg_logprob']}"
AssertionError: Fatal Error: Got inconsistent logprob for segment 543: -0.34706705808639526 != -0.2806609970571749
```

**Comment by Jeronymous** [comment]
What do you mean "It did not produce anything"?
It's failing with the exact same error as before.

What gives `pip show whisper-timestamped` now?
Did you upgrade to a newer version ? (for instance by running `pip install --upgrade --no-deps --force-reinstall git+https://github.com/linto-ai/whisper-timestamped`)

**Comment by MohammedMehdiTBER** [comment]
> What do you mean "It did not produce anything"? It's failing with the exact same error as before.
> 
> What gives `pip show whisper-timestamped` now? `whisper-timestamped -v`? Did you upgrade to a newer version ? (for instance by running `pip install --upgrade --no-deps --force-reinstall git+https://github.com/linto-ai/whisper-timestamped`)


```python
PS C:\Users\MohammedMehdiTBER> pip show whisper-timestamped
Name: whisper-timestamped
Version: 1.6.7
Summary: Add to OpenAI Whisper the capability to give word timestamps
Home-page: https://github.com/Jeronymous/whisper-timestamped
Author: Jeronymous
Author-email:
License: MIT
Location: c:\users\mohammedmehditber\appdata\roaming\python\python310\site-packages
Requires: Cython, dtw-python, openai-whisper
Required-by:
PS C:\Users\MohammedMehdiTBER>
```

**Comment by MohammedMehdiTBER** [comment]
Same error even with using python env:

```python
PS C:\Users\MohammedMehdiTBER\whisper-timestamped> pipenv --python "C:\Program Files\Python310\python.exe" install git+https://github.com/linto-ai/whisper-timestamped#egg=whisper-timestamped
Installing git+https://github.com/linto-ai/whisper-timestamped#egg=whisper-timestamped...
Pipfile.lock (5a35e3) out of date, updating to (30cd9b)...
Locking [packages] dependencies...
Locking [dev-packages] dependencies...
Updated Pipfile.lock (bcad4f480615786d5960b2ede41d5e61cddf802ff86a1fbbd9513f6d9b30cd9b)!
Installing dependencies from Pipfile.lock (30cd9b)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
PS C:\Users\MohammedMehdiTBER\whisper-timestamped> pipenv run
Usage: pipenv run [OPTIONS] COMMAND [ARGS]...
Try 'pipenv run -h' for help.

Error: Missing argument 'COMMAND'.
PS C:\Users\MohammedMehdiTBER\whisper-timestamped> pipenv shell
Launching subshell in virtual environment...
PowerShell 7.3.1
PS C:\Users\MohammedMehdiTBER> pipenv run -h
Usage: pipenv run [OPTIONS] COMMAND [ARGS]...

  Spawns a command installed into the virtualenv.

Options:
  --python TEXT       Specify which version of Python virtualenv should use.
  --three             Use Python 3 when creating virtualenv. Deprecated
  --clear             Clears caches (pipenv, pip).  [env var: PIPENV_CLEAR]
  -q, --quiet         Quiet mode.
  -v, --verbose       Verbose mode.
  --pypi-mirror TEXT  Specify a PyPI mirror.
  -h, --help          Show this message and exit.
PS C:\Users\MohammedMehdiTBER> whisper_timestamped "C:\Users\MohammedMehdiTBER\Downloads\نقد أغنية Begin Again Purity Ring.mp3" --model large-v2 --output_dir "C:\Users\MohammedMehdiTBER\Documents" --language Arabic --device cpu --threads 4 --verbose True
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\MohammedMehdiTBER\.virtualenvs\MohammedMehdiTBER-xIZJGCn3-python.exe\Scripts\whisper_timestamped.exe\__main__.py", line 7, in <module>
  File "C:\Users\MohammedMehdiTBER\.virtualenvs\MohammedMehdiTBER-xIZJGCn3-python.exe\lib\site-packages\whisper_timestamped\transcribe.py", line 1379, in cli
    result = transcribe_timestamped(
  File "C:\Users\MohammedMehdiTBER\.virtualenvs\MohammedMehdiTBER-xIZJGCn3-python.exe\lib\site-packages\whisper_timestamped\transcribe.py", line 211, in transcribe_timestamped
    (transcription, words) = _transcribe_timestamped_efficient(model, audio, **alignment_options, **whisper_options, **other_options)
  File "C:\Users\MohammedMehdiTBER\.virtualenvs\MohammedMehdiTBER-xIZJGCn3-python.exe\lib\site-packages\whisper_timestamped\transcribe.py", line 627, in _transcribe_timestamped_efficient
    assert abs(segment["avg_logprob"] - avglogprob) < 1e-2, f"Fatal Error: Got inconsistent logprob for segment {i}: {avglogprob} != {segment['avg_logprob']}"
AssertionError: Fatal Error: Got inconsistent logprob for segment 543: -0.34706705808639526 != -0.2806609970571749
```

**Comment by Jeronymous** [comment]
OK, sorry for the inconvenience.
I pushed a new version "1.7.0" that solves several issues including one related to the assertion failure you saw.

Can you please try?

Note: this version use different default options, so it is longer to run, and the transcription results should be better.
If you were OK with the accuracy of the transcription, and want to run faster, you should use option `--efficient`.

**Comment by MohammedMehdiTBER** [comment]
> OK, sorry for the inconvenience. I pushed a new version "1.7.0" that solves several issues including one related to the assertion failure you saw.
> 
> Can you please try?
> 
> Note: this version use different default options, so it is longer to run, and the transcription results should be better. If you were OK with the accuracy of the transcription, and want to run faster, you should use option `--efficient`.

Tried on 1.7.1. It worked via Google Colab now. I did not know about--efficient, so I did not use it, but I would like if the subtitles are more precise and do not fade before the speech ends.
